version: '3'
services:
     php1:
      build: .
      ports:
       - "80:80"
       - "443:443"
      volumes:
       - ./www:/var/www/html
      networks:
       phpnetwork:
         ipv4_address: 172.30.5.3
        
        
     php2:
      build: .
      ports:
       - "80:80"
       - "443:443"
      volumes:
       - ./www:/var/www/html
      networks:
       phpnetwork:
         ipv4_address: 172.30.5.4
         
     php3:
      build: .
      ports:
       - "80:80"
       - "443:443"
      volumes:
       - ./www:/var/www/html
      networks:
       phpnetwork:
         ipv4_address: 172.30.5.5



networks:
 phpnetwork:
  driver: bridge
  ipam:
   config:
    - subnet: 172.30.5.0/24
      gateway: 172.30.5.254
    
        