version: "3"
services:
    php:
      build: .
      ports:
       - "80:80"
       - "443:443"
      volumes:
       - ./www:/var/www/html
      networks:
       phpnetwork:
          ipv4_address: 172.30.1.2
networks:
  phpnetwork:
   driver: bridge
   ipam:
    config:
      - subnet: 172.30.1.0/24
        gateway: 172.30.1.1
    
        