version: '2'
services:
     php1:
      build: .
      ports:
       - "81:80"
       - "443:443"
      volumes:
       - ./www:/var/www/html
#      links:
#       - db
      networks:
       phpnetwork:
         ipv4_address: 172.30.5.3       
        
     php2:
      build: .
      ports:
       - "82:80"
       - "443:443"
      volumes:
       - ./www:/var/www/html
#      links:
#       - db
      networks:
       phpnetwork:
         ipv4_address: 172.30.5.4
         
     php3:
      build: .
      ports:
       - "83:80"
       - "443:443"
      volumes:
       - ./www:/var/www/html
#      links:
#       - db
      networks:
       phpnetwork:
         ipv4_address: 172.30.5.5
          
     haproxy1: 
      image: haproxy:1.7
      volumes:
       - ./haproxy1/haproxy.cfg:/usr/local/etc/haproxy/haproxy.cfg
       - ./haproxy1/conf.d:/usr/local/etc/haproxy/conf.d
      ports:
       - "8100:80"
      networks:
       phpnetwork:
         ipv4_address: 172.30.5.6
         
#      db:
#       image: mysql:5.7
#       volumes:
#        - /var/lib/mysql
#       environment:
#        - MYSQL_ROOT_PASSWORD=projeto
#        - MYSQL_DATABASE=projeto
#         ipv4_address: 172.30.5.5

networks:
 phpnetwork:
  driver: bridge
  ipam:
   config:
    - subnet: 172.30.5.0/24
      gateway: 172.30.5.254
    
        