version: '2'

services:

    php1: 
      dockerfile: Dockerfile 
      volumes:
        - .:/var/www/html
        - /etc/timezone:/etc/timezone
        - /etc/localtime:/etc/localtime

      build: .
      expose:
        - "80"
      ports:
        - "8080:80"
      environment: 
       - PHP_HOST=php1
       - PHP_PORT=80
      networks: 
       httpnetwork:
         ipv4_address: 172.30.5.3
         
    php2: 
      dockerfile: Dockerfile 
      volumes:
        - .:/var/www/html
        - /etc/timezone:/etc/timezone
        - /etc/localtime:/etc/localtime

      build: .
      expose:
        - "80"
      ports:
        - "8081:80"
      environment: 
       - PHP_HOST=php2
       - PHP_PORT=80
      networks: 
       httpnetwork:
         ipv4_address: 172.30.5.4
         
    haproxy1: 
      image: haproxy:1.7
      volumes:
       - ./haproxy1/haproxy.cfg:/usr/local/etc/haproxy/haproxy.cfg
       - ./haproxy1/conf.d:/usr/local/etc/haproxy/conf.d
      ports:
       - "8100:80"
      networks:
       httpnetwork:
         ipv4_address: 172.30.5.10

networks:
 httpnetwork:
#  driver: overlay
  driver: bridge
  ipam:
   config:
    - subnet: 172.30.0.0/16
      gateway: 172.30.5.254
#    - ip-range: 172.30.5.0/24
