version: '2'
services:
     php:
      build: .
      ports:
       - "80:80"
       - "443:443"
      volumes:
       - ./www:/var/www/html
      networks:
       httpnetwork:
         ipv4_address: 172.30.5.3

networks:
 phpnetwork:
  driver: bridge
  ipam:
   config:
    - subnet: 172.30.5.0/24
      gateway: 172.30.5.254
    
        